name: Update to upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-main-branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Fetch latest upstream version
        run: |
          echo "upstream_version=$(curl -sL https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest | jq -r ".tag_name")" >> "$GITHUB_ENV"
          echo "local_version=$(grep 'version:' snap/snapcraft.yaml | tail -n1 | cut -c10-)" >> "$GITHUB_ENV"
      - name: Bump snapcraft.yaml to latest upstream version
        if: ${{ env.upstream_version != env.local_version }}
        run: |
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            sed -i '2 s/.*/version: '$upstream_version'/' snap/snapcraft.yaml
            git add snap/snapcraft.yaml
            git commit -m "[BOT] Bump to v$upstream_version"
            git push -u origin main
  update-stable-branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'stable'
      - name: Fetch latest upstream version
        run: |
          echo "upstream_version=$(curl -sL https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest | jq -r ".tag_name")" >> "$GITHUB_ENV"
          echo "local_version=$(grep 'version:' snap/snapcraft.yaml | tail -n1 | cut -c10-)" >> "$GITHUB_ENV"
      - name: Bump snapcraft.yaml to latest upstream version
        if: ${{ env.upstream_version != env.local_version }}
        run: |
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            sed -i '2 s/.*/version: '$upstream_version'/' snap/snapcraft.yaml
            git add snap/snapcraft.yaml
            git commit -m "[BOT] Bump to v$upstream_version"
            git push -u origin stable
